version: "3"

tasks:
  build:
    desc: Build the skele
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/skele main.go

  run-exp:
    desc: Run the skele
    cmds:
      - GOFLAGS=-mod=mod go run main.go -e=true

  run-bot:
    desc: Execute the skele
    cmds:
      - ./bin/skele

  docker-build:
    desc: Build the skele with docker
    cmds:
      - docker build . -t skele-go:0.1

  docker-bot:
    desc: Execute the skele in a detached container
    cmds:
      - docker run -d skele-go:0.1

  docker-kill-latest:
    desc: Stops the detached skele-go bot container
    cmds:
      - docker stop $(docker ps -ql)
