name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Configure working directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            WORKING_DIR="skele-ci"
            REPO="skele"
            mkdir -p $WORKING_DIR
            cd $WORKING_DIR

            if [ ! -d $REPO ]; then
              echo "working dir is empty, cloning skele"
              git clone git@github.com:jaronaearle/skele.git
            else
              echo "working is exists, let check it out"
              cd $REPO
            fi

            pwd 
            ls
