name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Configure working directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            WORKING_DIR="skele-ci"
            REPO="skele"
            mkdir -p $WORKING_DIR
            cd $WORKING_DIR
            if [ ! -d $REPO ]; then
              echo "working directory is empty, cloning skele..."
              # git clone git@github.com:jaronaearle/skele.git
              cd $REPO
            else
              echo "repo exists, pulling latest changes..."
              cd $REPO
              git pull
            fi
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
            echo "HONEY_BADGER_API_KEY=${{ secrets.HONEY_BADGER_API_KEY }}" >> .env
            echo "PAPER_TRAIL_HOST=${{ secrets.PAPER_TRAIL_HOST }}" >> .env

            task docker-kill-latest

            task docker-build
            task docker-bot
            echo "Bot process $(docker ps -ql) started successfully"
