name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Skele Bot
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USER }} # User of the server you want to ssh into

          script: |
            mkdir -p skele-ci 
            cd skele-ci 
            git clone git@github.com:SkeleScript/skele-.git 
            ls -a 
            echo 'Deployment successful to digital ocean'
